# scraped from https://blog.orhun.dev/automated-rust-releases/
# thanks!
pull_request_rules:
  - name: Automatic merge for Dependabot pull requests when CI passes
    conditions:
      - author=dependabot[bot]
      # Only merge if CI checks pass
      - status-success=stable / fmt
      - status-success=stable + beta / clippy
      - status-success=nightly / doc
      - status-success=stable / check (Ubuntu)
      - status-success=stable / check (Windows)
    actions:
      merge:
        method: squash

  - name: Automatic update to the main branch for pull requests
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # skip GH draft PRs
      - -author=dependabot[bot] # skip dependabot PRs
    actions:
      update:
