[workspace]
members = ["sericom-core"]

[workspace.dependencies]
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
crossterm = { version = "0.29.0", features = ["osc52", "event-stream"] }
miette = { version = "7.6.0", features = ["fancy"] }
serde = { version = "1.0.219", features = ["derive"] }
serial2-tokio = { version = "0.1.15", features = ["windows"] }
thiserror = "2.0.16"
tokio = { version = "1.47.0", features = ["full"] }
toml = "0.9.5"


[workspace.package]
edition = "2024"
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/tkatter/sericom"
exclude = ["configuration/*", ".github/*"]


[package]
name = "sericom"
version = "0.2.0"
description = "CLI tool for communicating with devices over a serial connection."
keywords = ["serial", "console"]
categories = ["command-line-utilities"]
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
exclude.workspace = true

[package.metadata.deb]
maintainer = "Thomas Katter <tjkatter@gmail.com>"
copyright = "2025, Thomas Katter <tjkatter@gmail.com>"
license-file = ["LICENSE", "14"]

[dependencies]
sericom-core = { path = "./sericom-core" }
tokio.workspace = true
clap.workspace = true
serial2-tokio.workspace = true
miette.workspace = true
crossterm.workspace = true
# tracing = "0.1"
# console-subscriber = "0.4.1"
