[package]
name = "netcon"
version = "0.1.0"
edition = "2024"
description = "CLI tool for issuing commands to network switches and routers over their serial connections."

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
console-subscriber = "0.4.1"
crossterm = { version = "0.29.0", features = ["osc52", "event-stream"] }
serial2-tokio = { version = "0.1.15", features = ["windows"] }
tokio = { version = "1.47.0", features = ["full", "tracing"] }
tracing = "0.1"
