[package]
name = "sericom-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
chrono.workspace = true
crossterm.workspace = true
miette.workspace = true
serde.workspace = true
serial2-tokio.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
